
const blogData = {
  "Master the Perfect Freestyle: A Comprehensive Stroke Guide": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Olympic gold medalist and AquaRise head coach David Miller breaks down the perfect freestyle stroke into six actionable phases. From hand entry to hip rotation, every detail is covered to help you swim faster with less effort. This guide includes dry-land drills, common mistakes to avoid, and a progressive training plan used by national-level swimmers.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "10 Essential Beginner Swimming Tips for Adults": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Starting swimming as an adult can be daunting. Our coaches share practical advice to build confidence and progress quickly.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Perfect Freestyle Technique: Arm Pull Mechanics": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Learn the high-elbow catch and S-pull pattern that elite swimmers use to maximize propulsion with minimal effort.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Why Swimming is the Ultimate Full-Body Workout": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover how swimming burns calories, builds lean muscle, and improves cardiovascular health better than most land exercises.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Essential Pool Safety Guidelines Every Parent Should Know": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">From supervision rules to emergency preparedness, equip your family with these critical water safety practices.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "7 Surprising Mental Health Benefits of Regular Swimming": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Beyond physical fitness, swimming reduces anxiety, improves sleep, and boosts cognitive function. Here's the science.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "How to Improve Breathing Technique for Longer Swims": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Master bilateral breathing, exhalation patterns, and rhythmic timing to swim longer distances without fatigue.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Popular Posts": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Master the Perfect Freestyle Stroke": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "10 Beginner Swimming Tips for Adults": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Why Swimming is the Ultimate Workout": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Categories": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Popular Tags": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Follow Us": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Discover our latest insights, tips, and academy updates to improve your swimming journey.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Swimming Basics": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Fundamental techniques and water confidence for beginners.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Fitness Swimming": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Workout plans, cardio tips, and strength training in water.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Competition Training": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Race strategies, drills, and mental preparation for meets.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Kids Swimming": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Age-appropriate lessons, safety tips, and fun aquatic activities.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Nutrition": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Balanced meals with protein and complex carbs within 30 minutes post-swim.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Water Safety": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Pool rules, lifesaving skills, and emergency preparedness.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Warm-up Routine": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Dynamic stretches and light swimming to activate muscles before intense sets.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Stroke Improvement": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Focus on high-elbow catch and early vertical forearm for better propulsion.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Breathing Technique": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Practice bilateral breathing to balance your stroke and improve oxygen flow.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Recovery Tips": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Active recovery swims, stretching, and adequate sleep for muscle repair.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Hydration": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Drink water before, during, and after practice even in the pool environment.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Summer Swimming Camp": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Intensive 4-week summer program with daily training, games, and water sports for ages 6-16.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "National Championship Trials": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">AquaRise team selection trials for the upcoming National Swimming Championships.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "International Coach Workshop": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Professional development workshop for coaches featuring FINA-certified international trainers.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "New Batch Registration Open": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Enrollments open for the winter batch. Early bird discounts available for limited seats.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Annual Inter-Academy Swim Meet": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Annual swimming competition featuring teams from 12 partner academies across the region.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Annual Awards Ceremony": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Celebrating our swimmers' achievements with trophies, medals, and special recognitions.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  },
  "Stay Updated with AquaRise": {
    "content": "<p style=\"margin-bottom: 1.5rem; font-weight: 500; font-size: 1.2rem; color: var(--primary);\">Get the latest swimming tips, academy news, and exclusive offers delivered straight to your inbox.</p>\n    <p style=\"margin-bottom: 1.5rem;\">Swimming offers an unparalleled combination of cardiovascular training and full-body muscle engagement. While the water provides resistance to build strength, its buoyancy ensures that your joints remain protected from high-impact stress.</p>\n    <h3 style=\"margin-top: 2rem; margin-bottom: 1rem; color: var(--text);\">In-Depth Analysis</h3>\n    <p style=\"margin-bottom: 1.5rem;\">Consistent practice and dedicating time to mastering the fundamental techniques outlined above will yield significant improvements. Whether your goal is competitive racing, fitness, or simply enjoying the water, maintaining a structured approach is essential.</p>\n    <ul style=\"margin-bottom: 1.5rem; padding-left: 20px;\">\n      <li style=\"margin-bottom: 0.5rem;\">Focus on your breathing rhythm to maintain stamina.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Keep your core engaged to reduce drag in the water.</li>\n      <li style=\"margin-bottom: 0.5rem;\">Always incorporate a warm-up and cool-down phase into your routine.</li>\n    </ul>\n    <p style=\"margin-bottom: 1.5rem;\">Our certified instructors at AquaRise are always available to help you refine your strokes and achieve your personal aquatic goals. Keep practicing, and we'll see you at the pool!</p>"
  }
};

document.addEventListener('DOMContentLoaded', () => {
  const urlParams = new URLSearchParams(window.location.search);
  
  const title = urlParams.get('title');
  const img = urlParams.get('img');
  const date = urlParams.get('date');

  if (title) {
    const titleEl = document.getElementById('bd-title');
    const breadcrumbEl = document.getElementById('bd-breadcrumb-title');
    if (titleEl) titleEl.innerText = title;
    if (breadcrumbEl) breadcrumbEl.innerText = title;
  } else {
    document.getElementById('bd-title').innerText = 'Understanding Water Dynamics';
    document.getElementById('bd-breadcrumb-title').innerText = 'Understanding Water Dynamics';
  }

  if (img) {
    const imgEl = document.getElementById('bd-image');
    if (imgEl) imgEl.src = img;
  } else {
    const imgEl = document.getElementById('bd-image');
    if (imgEl) imgEl.src = 'https://i.pinimg.com/1200x/8d/e4/c3/8de4c377ed804d6d833e6efeb04051e7.jpg';
  }

  if (date) {
    const dateEl = document.getElementById('bd-date');
    if (dateEl) dateEl.innerHTML = `<i class="far fa-calendar"></i> ${date}`;
  } else {
    const dateEl = document.getElementById('bd-date');
    if (dateEl) dateEl.innerHTML = `<i class="far fa-calendar"></i> Today`;
  }
  
  // Inject unique content based on title
  const contentEl = document.querySelector('.blog-detail-content');
  if (contentEl && title && blogData[title]) {
    contentEl.innerHTML = blogData[title].content;
  }
});
